# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jason Hee
email: jasonheecs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Jason Hee, a Singaporean Web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jasonhee.com" # the base hostname & protocol for your site
github_username:  jasonheecs
codepen_username:  jasonheecs

# Build settings
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "_scss", "css", "_js"]
permalink: /:title/

# defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
- jekyll-email-protect